/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2uoRoUYmXRH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import Image from "next/image"
import NutritionCalculator from "./ui/calculator"
import { FacebookIcon, InstagramIcon } from "lucide-react"
export function GymPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] text-red-600">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b-2 border-red-200 bg-white fixed w-full">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <DumbbellIcon className="h-6 w-6" />
          <div className="text-black font-bold">UNO </div>
          <span className="sr-only">Fitness Gym</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#about" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#classes" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Classes
          </Link>
          <Link href="#contact" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4 bg-muted p-8 rounded-xl">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Unlock Your Fitness Potential
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Experience the ultimate fitness journey at our state-of-the-art gym. Reach your goals with our
                    expert trainers and cutting-edge facilities.
                  </p>
                </div>
               
              </div>
              <Image
                src="/hero.jpg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square border-4 border-red-500"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Experience the Best Gym in Town</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our state-of-the-art facility offers the latest equipment, expert trainers, and a wide range of
                  classes to help you reach your fitness goals.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <Image
                src="/UNO.png"
                width="550"
                height="310"
                alt="Gym Features"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">State-of-the-Art Equipment</h3>
                      <p className="text-muted-foreground">
                        Our gym is equipped with the latest and greatest fitness equipment to help you achieve your
                        goals.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Experienced Trainers</h3>
                      <p className="text-muted-foreground">
                        Our team of certified trainers are dedicated to helping you reach your full potential.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Diverse Class Schedule</h3>
                      <p className="text-muted-foreground">
                        From yoga to HIIT, we offer a wide range of classes to keep your workouts fresh and exciting.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Members Say</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Hear from our satisfied members about their experience at our gym.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">I ve never felt better!</h3>
                  <p className="text-muted-foreground">
                    Since joining this gym, I ve seen a dramatic improvement in my overall health and fitness. The
                    trainers are amazing and the facilities are top-notch.
                  </p>
                  <p className="text-sm text-muted-foreground">- Sarah, Member since 2020</p>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold">Truly life-changing!</h3>
                  <p className="text-muted-foreground">
                    I was hesitant to join a gym at first, but this place has completely transformed my life. The
                    community is so supportive, and I look forward to my workouts every day.
                  </p>
                  <p className="text-sm text-muted-foreground">- Michael, Member since 2018</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Nutrition Calculator</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Use our nutrition calculator to determine your daily calorie and macronutrient needs.
                </p>
              </div>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
                 <NutritionCalculator/>
            </div>
          </div>
        </section>
        <section id="classes" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Class Schedule</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out our weekly class schedule and sign up for the ones that fit your fitness goals.
                </p>
              </div>
            </div>
            <div className="mx-auto w-full max-w-4xl">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Time</TableHead>
              <TableHead>Monday</TableHead>
              <TableHead>Tuesday</TableHead>
              <TableHead>Wednesday</TableHead>
              <TableHead>Thursday</TableHead>
              <TableHead>Friday</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            
            <TableRow>
              <TableCell>6:30 PM</TableCell>
              <TableCell>Danse Orientale</TableCell>
              <TableCell>Spinning</TableCell>
              <TableCell>Body-Pump</TableCell>
              <TableCell>Body-Combat</TableCell>
              <TableCell>-</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>7:30 PM</TableCell>
              <TableCell>Circuit Training</TableCell>
              <TableCell>-</TableCell>
              <TableCell>-</TableCell>
              <TableCell>-</TableCell>
              <TableCell>Pilate/Yoga</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>

          </div>
        </section>
          <div className="flex flex-col min-h-dvh">
   
      <main className="flex-1">
        <section id="about" className="bg-muted py-12 md:py-24">
          <div className="container px-4 md:px-6 grid md:grid-cols-2 gap-8">
            <div>
              <h2 className="text-3xl font-bold mb-4">About Our Gym</h2>
              <p className="text-muted-foreground mb-6">
                Welcome to UNO Gym & Fitness, where we are dedicated to helping you achieve your fitness goals. Our
                state-of-the-art facility offers a wide range of equipment, classes, and personal training to cater to
                all your needs.
              </p>
              <p className="text-muted-foreground">
                Our experienced trainers are passionate about fitness and committed to providing you with the support
                and guidance you need to succeed. Join our community and embark on a journey towards a healthier,
                stronger you.
              </p>
            </div>
            <div>
              <div className="rounded-lg overflow-hidden aspect-video">
                <iframe
                  src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=uno%20gym%20manouba%20tunis+(uno%20gym%20&amp;%20fitness)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
                  width="100%"
                  height="100%"
                  frameBorder="0"
                  style={{ border: 0 }}
                  allowFullScreen
                  aria-hidden="false" 
                />
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <div className="flex items-center gap-4 mb-4">
                  <PhoneIcon className="h-6 w-6 text-muted-foreground" />
                  <div>
                    <h3 className="font-medium">Phone</h3>
                    <p className="text-muted-foreground"> +216 55 011 936</p>
                  </div>
                </div>
                
                <div className="flex items-center gap-4 mb-4">
                  <LocateIcon className="h-6 w-6 text-muted-foreground" />
                  <div>
                    <h3 className="font-medium">Address</h3>
                    <p className="text-muted-foreground">Avenue Habib Bourguiba Manouba</p>
                  </div>
                </div>
                <div className="flex items-center gap-4 mb-4">
                  <FacebookIcon className="h-6 w-6 text-muted-foreground" />
                  <div>
                    <h3 className="font-medium">Facebook</h3>
                    <Link className="text-muted-foreground" href={"https://www.facebook.com/profile.php?id=100063980775748"}>UNO Gym & Fitness </Link>
                  </div>
                </div>
                <div className="flex items-center gap-4 mb-4">
                  <InstagramIcon className="h-6 w-6 text-muted-foreground" />
                  <div>
                    <h3 className="font-medium">Instagram</h3>
                    <Link className="text-muted-foreground" href={"https://www.instagram.com/unogymfit/"}>unogymfit</Link>
                  </div>
                </div>
                <div className="flex items-center gap-4 mb-4">
                  <ClockIcon className="h-6 w-6 text-muted-foreground" />
                  <div>
                    <h3 className="font-medium">Hours</h3>
                    <p className="text-muted-foreground">
                      Monday - Friday: 8 am - 10 pm
                      <br />
                      Saturday: 8 am - 8 pm
                      <br />
                      Sunday: 8 am - 1 pm
                    </p>
                  </div>
                </div>
              </div>
              <div>
                
           
              </div>
            </div>
          </div>
        </section>
      </main>
    
    </div>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Get in Touch</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Have questions or want to schedule a tour? Fill out the form below and we ll get back to you as soon
                  as possible.
                </p>
              </div>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-4">
                <Input type="text" placeholder="Name" />
                <Input type="email" placeholder="Email" />
                <Textarea placeholder="Message" />
                <Button type="submit" className="self-end">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
       
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 UNO Gym & Fitness. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function DumbbellIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
function ClockIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


 


function LocateIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MailIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MenuIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PhoneIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


 